-- =============================================
-- PEMIRA UNBARA - E-VOTING DATABASE SCHEMA
-- =============================================
-- Author: Eleng
-- Version: 3.0 (Security Hardened + Anonymity Protected)
-- 
-- INSTRUKSI:
-- 1. Buat project baru di Supabase
-- 2. Buka SQL Editor di Supabase Dashboard
-- 3. Copy-paste SELURUH isi file ini
-- 4. Klik "Run"
-- 5. Daftarkan admin user via Authentication → Users, lalu 
--    INSERT INTO admin_users (user_id) VALUES ('<uuid dari auth.users>');
--
-- FITUR KEAMANAN:
-- ✓ Row Level Security (RLS) pada semua tabel
-- ✓ Dual Rate Limiting (per-NIM + per-Device)
-- ✓ Anonimitas suara (votes tanpa timestamp, audit tanpa korelasi)
-- ✓ BCrypt hashing untuk kode akses
-- ✓ SECURITY DEFINER functions dengan search_path terkunci
-- ✓ Validasi candidate_id sebelum INSERT
-- ✓ Audit trail terpisah dari data suara
-- =============================================

-- =============================================
-- 1. SETUP EKSTENSI
-- =============================================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================
-- 2. TIPE DATA (ENUM)
-- =============================================
DO $$
BEGIN
  CREATE TYPE log_type AS ENUM (
    'LOGIN_FAIL',
    'VOTE_SUCCESS',
    'SYSTEM_ERROR',
    'ADMIN_ACTION',
    'SECURITY_ALERT'
  );
EXCEPTION
  WHEN duplicate_object THEN NULL;
END $$;

-- =============================================
-- 3. TABEL - CANDIDATES (Paslon)
-- =============================================
CREATE TABLE IF NOT EXISTS candidates (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_number int NOT NULL,
  chairman_name text NOT NULL,
  vice_chairman_name text NOT NULL DEFAULT '',
  vision text NOT NULL,
  mission text NOT NULL,
  photo_url text,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- =============================================
-- 4. TABEL - VOTERS (DPT Mahasiswa)
-- =============================================
CREATE TABLE IF NOT EXISTS voters (
  nim text PRIMARY KEY,
  name text NOT NULL,
  faculty text NOT NULL DEFAULT 'Unknown',
  major text NOT NULL DEFAULT 'Unknown',
  access_code_hash text NOT NULL,
  has_voted boolean DEFAULT false NOT NULL,
  voted_at timestamptz,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_voters_faculty ON voters (faculty);
CREATE INDEX IF NOT EXISTS idx_voters_has_voted ON voters (has_voted);

-- =============================================
-- 5. TABEL - RATE LIMITS (Anti Brute Force)
-- Dual key strategy:
--   'nim:<nim>'        → rate limit per akun target
--   'dev:<hash>'       → rate limit per device/IP
-- =============================================
CREATE TABLE IF NOT EXISTS vote_rate_limits (
  client_key text PRIMARY KEY,
  fail_count int DEFAULT 0 NOT NULL,
  first_fail_at timestamptz,
  blocked_until timestamptz,
  updated_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_rate_limits_blocked ON vote_rate_limits (blocked_until)
  WHERE blocked_until IS NOT NULL;

-- =============================================
-- 6. TABEL - VOTES (Suara Anonim)
-- PENTING: Tidak ada kolom timestamp untuk mencegah
-- korelasi temporal dengan audit_logs (menjaga anonimitas)
-- =============================================
CREATE TABLE IF NOT EXISTS votes (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  candidate_id bigint REFERENCES candidates(id) ON DELETE CASCADE NOT NULL
);

-- =============================================
-- 7. TABEL - AUDIT LOGS
-- =============================================
CREATE TABLE IF NOT EXISTS audit_logs (
  id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
  action log_type NOT NULL,
  details jsonb,
  created_at timestamptz DEFAULT now() NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_action ON audit_logs (action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON audit_logs (created_at DESC);

-- =============================================
-- 8. TABEL - ELECTION SETTINGS
-- =============================================
CREATE TABLE IF NOT EXISTS election_settings (
  id int PRIMARY KEY DEFAULT 1,
  is_voting_open boolean DEFAULT false NOT NULL,
  show_live_result boolean DEFAULT false NOT NULL,
  updated_at timestamptz DEFAULT now() NOT NULL,
  CONSTRAINT single_row CHECK (id = 1)
);

INSERT INTO election_settings (id) VALUES (1) ON CONFLICT (id) DO NOTHING;

-- =============================================
-- 9. TABEL - ADMIN USERS
-- =============================================
CREATE TABLE IF NOT EXISTS admin_users (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  role text DEFAULT 'admin' NOT NULL,
  created_at timestamptz DEFAULT now() NOT NULL
);

-- =============================================
-- 10. ROW LEVEL SECURITY (RLS)
-- =============================================
ALTER TABLE candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE voters ENABLE ROW LEVEL SECURITY;
ALTER TABLE vote_rate_limits ENABLE ROW LEVEL SECURITY;
ALTER TABLE votes ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE election_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE admin_users ENABLE ROW LEVEL SECURITY;

-- Helper: Check Admin
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT EXISTS (SELECT 1 FROM admin_users WHERE user_id = auth.uid());
$$;

-- =============================================
-- 11. RLS POLICIES
-- =============================================

-- CANDIDATES
CREATE POLICY "Public view candidates" ON candidates FOR SELECT USING (true);
CREATE POLICY "Admin manage candidates" ON candidates FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- VOTERS
-- PENTING: voters TIDAK boleh bisa di-SELECT publik (berisi PII + access_code_hash).
-- Halaman publik hanya butuh JUMLAH pemilih, disediakan via RPC get_dpt_count().
CREATE POLICY "Admin modify voters" ON voters FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- VOTES
CREATE POLICY "Admin view votes" ON votes FOR SELECT TO authenticated USING (is_admin());

-- AUDIT LOGS
CREATE POLICY "Admin view logs" ON audit_logs FOR SELECT TO authenticated USING (is_admin());

-- ELECTION SETTINGS
CREATE POLICY "Public view settings" ON election_settings FOR SELECT USING (true);
CREATE POLICY "Admin update settings" ON election_settings FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());

-- ADMIN USERS
CREATE POLICY "Admin view self" ON admin_users FOR SELECT TO authenticated USING (user_id = auth.uid());

-- RATE LIMITS (managed by SECURITY DEFINER functions only)
CREATE POLICY "System manage rate limits" ON vote_rate_limits FOR ALL USING (true) WITH CHECK (true);

-- =============================================
-- 12. FUNCTION: submit_vote (Core Voting)
-- =============================================
-- Fixes applied:
--   ✓ Dual rate limiting (per-NIM + per-device)
--   ✓ Candidate validation before INSERT
--   ✓ Anonimitas: audit log terpisah dari vote record (no shared timestamp)
--   ✓ Proper blocked_until handling in single UPSERT
-- =============================================
CREATE OR REPLACE FUNCTION submit_vote(
  p_nim text,
  p_access_code_plain text,
  p_candidate_id bigint,
  p_client_info jsonb
) RETURNS jsonb AS $$
DECLARE
  v_voter voters%ROWTYPE;
  v_settings election_settings%ROWTYPE;
  v_rate vote_rate_limits%ROWTYPE;
  v_device_key text;
  v_nim_key text;
  v_ip text;
  v_ua text;
  v_now timestamptz := now();
  v_window interval := interval '10 minutes';
  v_max_fail_device int := 10;
  v_max_fail_nim int := 5;
  v_candidate_exists boolean;
BEGIN
  -- 1. Cek voting open
  SELECT * INTO v_settings FROM election_settings WHERE id = 1;
  IF v_settings.is_voting_open IS DISTINCT FROM true THEN
    INSERT INTO audit_logs (action, details) VALUES ('LOGIN_FAIL', jsonb_build_object('reason', 'Voting Closed', 'nim', p_nim));
    RETURN jsonb_build_object('status', 'error', 'message', 'Pemilihan suara sedang ditutup.');
  END IF;

  -- 2. Build rate limit keys (DUAL: per-device AND per-NIM)
  v_ip := COALESCE(p_client_info->>'ip', 'unknown');
  v_ua := COALESCE(p_client_info->>'userAgent', 'unknown');
  v_device_key := 'dev:' || encode(digest(v_ip || '|' || v_ua, 'sha256'), 'hex');
  v_nim_key := 'nim:' || encode(digest(p_nim, 'sha256'), 'hex');

  -- 3. Rate limit check: per-device
  SELECT * INTO v_rate FROM vote_rate_limits WHERE client_key = v_device_key;
  IF FOUND AND v_rate.blocked_until > v_now THEN
    INSERT INTO audit_logs (action, details) VALUES ('SECURITY_ALERT', jsonb_build_object('reason', 'Rate Limited (Device)', 'ip', v_ip));
    RETURN jsonb_build_object('status', 'error', 'message', 'Terlalu banyak percobaan gagal. Silakan tunggu 10 menit.');
  END IF;

  -- 4. Rate limit check: per-NIM
  SELECT * INTO v_rate FROM vote_rate_limits WHERE client_key = v_nim_key;
  IF FOUND AND v_rate.blocked_until > v_now THEN
    INSERT INTO audit_logs (action, details) VALUES ('SECURITY_ALERT', jsonb_build_object('reason', 'Rate Limited (NIM)', 'nim', p_nim));
    RETURN jsonb_build_object('status', 'error', 'message', 'Akun ini terkunci sementara karena terlalu banyak percobaan gagal.');
  END IF;

  -- 5. Validate NIM (with row lock to prevent race condition)
  SELECT * INTO v_voter FROM voters WHERE nim = p_nim FOR UPDATE;
  
  IF NOT FOUND THEN
    -- Increment BOTH rate limits
    PERFORM _increment_rate_limit(v_device_key, v_max_fail_device, v_window, v_now);
    PERFORM _increment_rate_limit(v_nim_key, v_max_fail_nim, v_window, v_now);
    
    INSERT INTO audit_logs (action, details) VALUES ('LOGIN_FAIL', jsonb_build_object('reason', 'NIM Not Found', 'nim', p_nim, 'ip', v_ip));
    RETURN jsonb_build_object('status', 'error', 'message', 'NIM tidak terdaftar dalam DPT.');
  END IF;

  -- 6. Validate Token (BCrypt comparison)
  IF v_voter.access_code_hash != crypt(p_access_code_plain, v_voter.access_code_hash) THEN
    PERFORM _increment_rate_limit(v_device_key, v_max_fail_device, v_window, v_now);
    PERFORM _increment_rate_limit(v_nim_key, v_max_fail_nim, v_window, v_now);

    INSERT INTO audit_logs (action, details) VALUES ('LOGIN_FAIL', jsonb_build_object('reason', 'Wrong Token', 'nim', p_nim, 'ip', v_ip));
    RETURN jsonb_build_object('status', 'error', 'message', 'Kode Akses salah.');
  END IF;

  -- 7. Check already voted
  IF v_voter.has_voted THEN
    INSERT INTO audit_logs (action, details) VALUES ('LOGIN_FAIL', jsonb_build_object('reason', 'Already Voted', 'nim', p_nim, 'ip', v_ip));
    RETURN jsonb_build_object('status', 'error', 'message', 'Mahasiswa ini sudah menggunakan hak pilihnya.');
  END IF;

  -- 8. Validate candidate exists
  SELECT EXISTS (SELECT 1 FROM candidates WHERE id = p_candidate_id) INTO v_candidate_exists;
  IF NOT v_candidate_exists THEN
    RETURN jsonb_build_object('status', 'error', 'message', 'Kandidat tidak valid.');
  END IF;

  -- 9. SUCCESS: Record vote (anonymously - no timestamp in votes table)
  DELETE FROM vote_rate_limits WHERE client_key IN (v_device_key, v_nim_key);
  UPDATE voters SET has_voted = true, voted_at = v_now WHERE nim = p_nim;
  INSERT INTO votes (candidate_id) VALUES (p_candidate_id);

  -- 10. Audit log (hanya fakultas, tanpa NIM untuk privasi tambahan)
  INSERT INTO audit_logs (action, details) 
  VALUES ('VOTE_SUCCESS', jsonb_build_object('faculty', v_voter.faculty, 'ip', v_ip));

  RETURN jsonb_build_object('status', 'success', 'message', 'Suara berhasil direkam. Terima kasih!');
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions;

-- =============================================
-- 13. HELPER: _increment_rate_limit (internal)
-- =============================================
CREATE OR REPLACE FUNCTION _increment_rate_limit(
  p_key text,
  p_max_fail int,
  p_window interval,
  p_now timestamptz
) RETURNS void AS $$
BEGIN
  INSERT INTO vote_rate_limits (client_key, fail_count, first_fail_at, updated_at, blocked_until)
  VALUES (p_key, 1, p_now, p_now, NULL)
  ON CONFLICT (client_key) DO UPDATE
  SET 
    fail_count = vote_rate_limits.fail_count + 1,
    updated_at = p_now,
    blocked_until = CASE 
      WHEN (vote_rate_limits.fail_count + 1) >= p_max_fail THEN p_now + p_window
      ELSE vote_rate_limits.blocked_until
    END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- =============================================
-- 14. FUNCTION: validate_voter (Pre-login Check)
-- =============================================
-- Fixes applied:
--   ✓ FOUND variable saved before UPSERT overwrites it
--   ✓ Dual rate limiting (per-NIM + per-device)
--   ✓ Proper error differentiation (NIM not found vs wrong token)
-- =============================================
CREATE OR REPLACE FUNCTION validate_voter(
  p_nim text,
  p_access_code_plain text,
  p_client_info jsonb DEFAULT '{}'::jsonb
) RETURNS jsonb AS $$
DECLARE
  v_voter voters%ROWTYPE;
  v_rate vote_rate_limits%ROWTYPE;
  v_device_key text;
  v_nim_key text;
  v_ip text;
  v_ua text;
  v_now timestamptz := now();
  v_window interval := interval '10 minutes';
  v_max_fail_device int := 10;
  v_max_fail_nim int := 5;
  v_voter_found boolean;
BEGIN
  -- Build rate limit keys
  v_ip := COALESCE(p_client_info->>'ip', 'unknown');
  v_ua := COALESCE(p_client_info->>'userAgent', 'unknown');
  v_device_key := 'dev:' || encode(digest(v_ip || '|' || v_ua, 'sha256'), 'hex');
  v_nim_key := 'nim:' || encode(digest(p_nim, 'sha256'), 'hex');

  -- 1. Check if device is blocked
  SELECT * INTO v_rate FROM vote_rate_limits WHERE client_key = v_device_key;
  IF FOUND AND v_rate.blocked_until > v_now THEN
    INSERT INTO audit_logs (action, details) VALUES ('SECURITY_ALERT', jsonb_build_object('reason', 'Rate Limited (Device)', 'ip', v_ip));
    RETURN jsonb_build_object('ok', false, 'reason', 'Terlalu banyak percobaan. Tunggu 10 menit.');
  END IF;

  -- 2. Check if NIM is blocked
  SELECT * INTO v_rate FROM vote_rate_limits WHERE client_key = v_nim_key;
  IF FOUND AND v_rate.blocked_until > v_now THEN
    INSERT INTO audit_logs (action, details) VALUES ('SECURITY_ALERT', jsonb_build_object('reason', 'Rate Limited (NIM)', 'nim', p_nim));
    RETURN jsonb_build_object('ok', false, 'reason', 'Akun terkunci sementara. Tunggu 10 menit.');
  END IF;

  -- 3. Validate NIM
  SELECT * INTO v_voter FROM voters WHERE nim = p_nim;
  v_voter_found := FOUND;
  
  -- 4. If NIM not found OR Token mismatch → increment both rate limits
  IF NOT v_voter_found OR v_voter.access_code_hash != crypt(p_access_code_plain, v_voter.access_code_hash) THEN
    PERFORM _increment_rate_limit(v_device_key, v_max_fail_device, v_window, v_now);
    PERFORM _increment_rate_limit(v_nim_key, v_max_fail_nim, v_window, v_now);

    -- Log specific error
    IF NOT v_voter_found THEN
      INSERT INTO audit_logs (action, details) VALUES ('LOGIN_FAIL', jsonb_build_object('reason', 'NIM Not Found', 'nim', p_nim, 'ip', v_ip));
      RETURN jsonb_build_object('ok', false, 'reason', 'NIM tidak ditemukan.');
    ELSE
      INSERT INTO audit_logs (action, details) VALUES ('LOGIN_FAIL', jsonb_build_object('reason', 'Wrong Token', 'nim', p_nim, 'ip', v_ip));
      RETURN jsonb_build_object('ok', false, 'reason', 'Kode Akses salah.');
    END IF;
  END IF;
  
  -- 5. Success: Reset rate limits for this client
  DELETE FROM vote_rate_limits WHERE client_key IN (v_device_key, v_nim_key);

  RETURN jsonb_build_object(
    'ok', true, 
    'has_voted', v_voter.has_voted, 
    'name', v_voter.name,
    'faculty', v_voter.faculty
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions;

-- =============================================
-- 15. FUNCTION: admin_add_voter (Import DPT)
-- =============================================
CREATE OR REPLACE FUNCTION admin_add_voter(
  p_nim text,
  p_name text,
  p_faculty text,
  p_major text,
  p_access_code_plain text
) RETURNS void AS $$
BEGIN
  -- Defense-in-depth: fungsi ini SECURITY DEFINER (bypass RLS),
  -- jadi pastikan caller benar-benar admin meski sudah dibatasi GRANT.
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Unauthorized: admin only';
  END IF;

  INSERT INTO voters (nim, name, faculty, major, access_code_hash)
  VALUES (
    p_nim,
    p_name,
    COALESCE(NULLIF(p_faculty, ''), 'Unknown'),
    COALESCE(NULLIF(p_major, ''), 'Unknown'),
    crypt(p_access_code_plain, gen_salt('bf'))
  )
  ON CONFLICT (nim) DO UPDATE
  SET name = EXCLUDED.name,
      faculty = EXCLUDED.faculty,
      major = EXCLUDED.major,
      access_code_hash = EXCLUDED.access_code_hash;
      
  INSERT INTO audit_logs (action, details) VALUES ('ADMIN_ACTION', jsonb_build_object('type', 'UPSERT_VOTER', 'nim', p_nim));
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, extensions;

-- =============================================
-- 16. FUNCTION: get_vote_recap (Real Count)
-- =============================================
-- Enforces show_live_result at DB level (not just frontend)
-- Admin always sees real data regardless of setting
-- =============================================
CREATE OR REPLACE FUNCTION get_vote_recap()
RETURNS TABLE (
  candidate_id bigint, 
  candidate_number int,
  chairman_name text,
  vice_chairman_name text,
  photo_url text,
  total_votes bigint
) AS $$
DECLARE
  v_show_live boolean;
  v_is_admin boolean;
BEGIN
  -- Check if caller is admin
  v_is_admin := EXISTS (SELECT 1 FROM admin_users WHERE user_id = auth.uid());

  -- Non-admin: enforce show_live_result setting
  IF NOT v_is_admin THEN
    SELECT es.show_live_result INTO v_show_live FROM election_settings es WHERE es.id = 1;
    IF v_show_live IS DISTINCT FROM true THEN
      RETURN QUERY
      SELECT c.id, c.candidate_number, c.chairman_name, c.vice_chairman_name, c.photo_url, 0::bigint AS total_votes
      FROM candidates c
      ORDER BY c.candidate_number;
      RETURN;
    END IF;
  END IF;

  RETURN QUERY
  SELECT 
    c.id,
    c.candidate_number,
    c.chairman_name,
    c.vice_chairman_name,
    c.photo_url,
    count(v.id)::bigint AS total_votes
  FROM candidates c
  LEFT JOIN votes v ON c.id = v.candidate_id
  GROUP BY c.id, c.candidate_number, c.chairman_name, c.vice_chairman_name, c.photo_url
  ORDER BY total_votes DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- =============================================
-- 17. FUNCTION: get_participation_stats
-- =============================================
CREATE OR REPLACE FUNCTION get_participation_stats()
RETURNS TABLE (
  faculty text,
  total_voters bigint,
  already_voted bigint,
  participation_percentage numeric
) AS $$
BEGIN
  -- Defense-in-depth: hanya admin yang boleh melihat statistik partisipasi.
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Unauthorized: admin only';
  END IF;

  RETURN QUERY
  SELECT
    v.faculty,
    count(*)::bigint AS total_voters,
    count(CASE WHEN v.has_voted THEN 1 END)::bigint AS already_voted,
    round((count(CASE WHEN v.has_voted THEN 1 END)::numeric / NULLIF(count(*)::numeric, 0)) * 100, 2) AS participation_percentage
  FROM voters v
  GROUP BY v.faculty
  ORDER BY participation_percentage DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- =============================================
-- 17b. FUNCTION: get_dpt_count (Total DPT untuk halaman publik)
-- =============================================
-- voters tidak public-readable, jadi halaman publik (Home/Results)
-- memakai fungsi ini untuk menampilkan jumlah pemilih terdaftar saja.
CREATE OR REPLACE FUNCTION get_dpt_count()
RETURNS bigint
LANGUAGE sql
SECURITY DEFINER
STABLE
SET search_path = public
AS $$
  SELECT count(*)::bigint FROM voters;
$$;

-- =============================================
-- 18. GRANT PERMISSIONS
-- =============================================
-- admin_add_voter: hanya authenticated (admin)
-- PENTING: REVOKE dari 'public' saja TIDAK cukup di Supabase, karena role
-- 'anon' & 'authenticated' mendapat GRANT EXECUTE default secara eksplisit.
-- Harus REVOKE eksplisit dari 'anon' untuk mencegah Broken Access Control (OWASP A01).
REVOKE ALL ON FUNCTION admin_add_voter(text, text, text, text, text) FROM public;
REVOKE EXECUTE ON FUNCTION admin_add_voter(text, text, text, text, text) FROM anon;
GRANT EXECUTE ON FUNCTION admin_add_voter(text, text, text, text, text) TO authenticated;

-- submit_vote: anon (voter belum login supabase auth) + authenticated
REVOKE ALL ON FUNCTION submit_vote(text, text, bigint, jsonb) FROM public;
GRANT EXECUTE ON FUNCTION submit_vote(text, text, bigint, jsonb) TO anon, authenticated;

-- get_vote_recap: publik (tapi di-enforce oleh function logic)
REVOKE ALL ON FUNCTION get_vote_recap() FROM public;
GRANT EXECUTE ON FUNCTION get_vote_recap() TO anon, authenticated;

-- get_participation_stats: hanya admin
REVOKE ALL ON FUNCTION get_participation_stats() FROM public;
REVOKE EXECUTE ON FUNCTION get_participation_stats() FROM anon;
GRANT EXECUTE ON FUNCTION get_participation_stats() TO authenticated;

-- validate_voter: anon (dipakai saat login voter)
REVOKE ALL ON FUNCTION validate_voter(text, text, jsonb) FROM public;
GRANT EXECUTE ON FUNCTION validate_voter(text, text, jsonb) TO anon, authenticated;

-- get_dpt_count: publik (hanya mengembalikan angka jumlah DPT)
REVOKE ALL ON FUNCTION get_dpt_count() FROM public;
GRANT EXECUTE ON FUNCTION get_dpt_count() TO anon, authenticated;

-- _increment_rate_limit: internal helper, no external access
-- Hanya dipanggil dari dalam submit_vote/validate_voter (SECURITY DEFINER),
-- jadi anon & authenticated harus di-revoke agar tidak bisa dipanggil via REST RPC.
REVOKE ALL ON FUNCTION _increment_rate_limit(text, int, interval, timestamptz) FROM public;
REVOKE EXECUTE ON FUNCTION _increment_rate_limit(text, int, interval, timestamptz) FROM anon;
REVOKE EXECUTE ON FUNCTION _increment_rate_limit(text, int, interval, timestamptz) FROM authenticated;

-- =============================================
-- 19. TRIGGERS - AUTOMATIC AUDIT LOGGING
-- =============================================
-- Only logs actual ADMIN actions (checks auth.uid() is admin)
-- Prevents noise from system operations (submit_vote updating voters)
-- =============================================
CREATE OR REPLACE FUNCTION log_admin_action_trigger()
RETURNS TRIGGER AS $$
DECLARE
  v_details jsonb;
  v_action text;
  v_is_admin boolean;
BEGIN
  -- Only log if current user is admin (prevents system operation noise)
  v_is_admin := EXISTS (SELECT 1 FROM admin_users WHERE user_id = auth.uid());
  IF NOT v_is_admin THEN
    RETURN NULL;
  END IF;

  v_action := TG_OP;

  -- Build details JSON based on table and operation
  IF TG_TABLE_NAME = 'candidates' THEN
    IF v_action = 'DELETE' THEN
      v_details := jsonb_build_object('table', 'candidates', 'op', 'DELETE', 'id', OLD.id, 'name', OLD.chairman_name);
    ELSE
      v_details := jsonb_build_object('table', 'candidates', 'op', v_action, 'id', NEW.id, 'name', NEW.chairman_name);
    END IF;

  ELSIF TG_TABLE_NAME = 'voters' THEN
    IF v_action = 'DELETE' THEN
      v_details := jsonb_build_object('table', 'voters', 'op', 'DELETE', 'nim', OLD.nim);
    ELSE
      v_details := jsonb_build_object('table', 'voters', 'op', v_action, 'nim', COALESCE(NEW.nim, OLD.nim));
    END IF;

  ELSIF TG_TABLE_NAME = 'election_settings' THEN
    v_details := jsonb_build_object(
      'table', 'election_settings', 
      'op', 'UPDATE', 
      'voting_open', NEW.is_voting_open, 
      'live_result', NEW.show_live_result
    );

  ELSIF TG_TABLE_NAME = 'admin_users' THEN
    IF v_action = 'DELETE' THEN
      v_details := jsonb_build_object('table', 'admin_users', 'op', 'DELETE', 'user_id', OLD.user_id);
    ELSE
      v_details := jsonb_build_object('table', 'admin_users', 'op', v_action, 'user_id', NEW.user_id);
    END IF;
  END IF;

  INSERT INTO audit_logs (action, details)
  VALUES ('ADMIN_ACTION', v_details);

  RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public;

-- Attach Triggers
CREATE TRIGGER audit_candidates_trigger
AFTER INSERT OR UPDATE OR DELETE ON candidates
FOR EACH ROW EXECUTE FUNCTION log_admin_action_trigger();

CREATE TRIGGER audit_settings_trigger
AFTER UPDATE ON election_settings
FOR EACH ROW EXECUTE FUNCTION log_admin_action_trigger();

CREATE TRIGGER audit_admin_users_trigger
AFTER INSERT OR UPDATE OR DELETE ON admin_users
FOR EACH ROW EXECUTE FUNCTION log_admin_action_trigger();

CREATE TRIGGER audit_voters_trigger
AFTER INSERT OR UPDATE OR DELETE ON voters
FOR EACH ROW EXECUTE FUNCTION log_admin_action_trigger();

-- =============================================
-- 20. STORAGE BUCKET (untuk foto kandidat)
-- =============================================
-- Jalankan ini terpisah jika perlu:
-- INSERT INTO storage.buckets (id, name, public) VALUES ('candidate-photos', 'candidate-photos', true);

-- =============================================
-- SELESAI! 
-- Langkah selanjutnya:
-- 1. Buat user admin di Authentication → Users
-- 2. Jalankan: INSERT INTO admin_users (user_id) VALUES ('<uuid>');
-- 3. Buat bucket 'candidate-photos' di Storage (set public)
-- 4. Update .env frontend dengan URL dan anon key baru
-- =============================================
SELECT 'Database migration completed successfully!' AS status;