-- =============================================
-- 1. SETUP EKSTENSI & ENUM
-- =============================================
-- Mengaktifkan ekstensi untuk hashing password/token (OWASP A02: Cryptographic Failures)
create extension if not exists "pgcrypto";

-- Enum untuk tipe log (agar rapi)
do $$
begin
  create type log_type as enum ('LOGIN_FAIL', 'VOTE_SUCCESS', 'SYSTEM_ERROR', 'ADMIN_ACTION');
exception
  when duplicate_object then null;
end $$;

-- =============================================
-- 2. PEMBUATAN TABEL (SCHEMA)
-- =============================================

-- A. TABEL KANDIDAT (Data Calon Kades)
-- Bersifat publik (bisa dilihat semua orang), tapi hanya admin yang bisa edit.
create table if not exists candidates (
  id bigint generated by default as identity primary key,
  name text not null,
  vision text not null, -- Visi
  mission text not null, -- Misi
  photo_url text, -- URL gambar dari Supabase Storage
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- B. TABEL PEMILIH (DPT - Daftar Pemilih Tetap)
-- SANGAT RAHASIA. Berisi NIM dan Hash Kode Akses.
create table if not exists voters (
  nim text primary key, -- NIM jadi Primary Key biar gak ada data ganda
  name text not null,
  access_code_hash text not null, -- Kita simpan HASH-nya, bukan kode aslinya!
  has_voted boolean default false not null, -- Indikator status memilih
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists vote_rate_limits (
  client_key text primary key,
  fail_count int default 0 not null,
  first_fail_at timestamp with time zone,
  blocked_until timestamp with time zone,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create index if not exists vote_rate_limits_blocked_until_idx
on vote_rate_limits (blocked_until);

-- C. TABEL SUARA (VOTES)
-- ANONIM. Tidak ada kolom 'nim' atau 'user_id' disini. (LUBER)
create table if not exists votes (
  id uuid default gen_random_uuid() primary key,
  candidate_id bigint references candidates(id) on delete cascade not null,
  timestamp timestamp with time zone default timezone('utc'::text, now()) not null
);

-- D. TABEL AUDIT LOG (SYSTEM LOGS)
-- Untuk merekam jejak aktivitas mencurigakan (OWASP A09: Security Logging)
create table if not exists audit_logs (
  id uuid default gen_random_uuid() primary key,
  action log_type not null,
  details jsonb, -- Simpan detail IP address, browser agent, dll disini
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table if not exists election_settings (
  id int primary key default 1,
  is_voting_open boolean default false not null,
  show_live_result boolean default false not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

insert into election_settings (id) values (1)
on conflict (id) do nothing;

create table if not exists admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- =============================================
-- 3. KEAMANAN: ROW LEVEL SECURITY (RLS)
-- =============================================
-- Aktifkan RLS di semua tabel (Default: Deny All)
alter table candidates enable row level security;
alter table voters enable row level security;
alter table vote_rate_limits enable row level security;
alter table votes enable row level security;
alter table audit_logs enable row level security;
alter table election_settings enable row level security;
alter table admin_users enable row level security;

create or replace function is_admin()
returns boolean
language sql
stable
as $$
  select exists (select 1 from admin_users au where au.user_id = auth.uid());
$$;

-- POLICY 1: Candidates
-- Semua orang (anon/public) boleh LIHAT data kandidat
drop policy if exists "Public can view candidates" on candidates;
create policy "Public can view candidates" 
on candidates for select 
to anon, authenticated 
using (true);

-- Hanya Admin (authenticated service_role) yang boleh EDIT/TAMBAH kandidat
-- (Nanti kita atur role admin via Dashboard Authentication)
drop policy if exists "Only admin can manage candidates" on candidates;
create policy "Only admin can manage candidates" 
on candidates for all 
to service_role 
using (true);

drop policy if exists "Admin users can manage candidates" on candidates;
create policy "Admin users can manage candidates"
on candidates for all
to authenticated
using (is_admin())
with check (is_admin());

-- POLICY 2: Voters
-- HATI-HATI: Jangan izinkan SELECT publik ke tabel voters!
-- Tabel ini hanya boleh diakses via Fungsi RPC (Function) di bawah.
-- Jadi kita biarkan policy-nya kosong untuk 'anon', artinya DENY ALL secara default.
drop policy if exists "Service role can manage voters" on voters;
create policy "Service role can manage voters" 
on voters for all 
to service_role 
using (true);

drop policy if exists "Admin users can view voters" on voters;
create policy "Admin users can view voters"
on voters for select
to authenticated
using (is_admin());

drop policy if exists "Admin users can update voters" on voters;
create policy "Admin users can update voters"
on voters for update
to authenticated
using (is_admin())
with check (is_admin());

drop policy if exists "Admin users can delete voters" on voters;
create policy "Admin users can delete voters"
on voters for delete
to authenticated
using (is_admin());

-- POLICY 3: Votes
-- User tidak boleh insert langsung ke tabel votes. Harus via fungsi vote.
-- Admin (service_role) boleh baca untuk rekapitulasi.
drop policy if exists "Service role can view votes" on votes;
create policy "Service role can view votes" 
on votes for select 
to service_role 
using (true);

drop policy if exists "Admin users can view audit logs" on audit_logs;
create policy "Admin users can view audit logs"
on audit_logs for select
to authenticated
using (is_admin());

drop policy if exists "Public can view election settings" on election_settings;
create policy "Public can view election settings"
on election_settings for select
to anon, authenticated
using (true);

drop policy if exists "Admin users can update election settings" on election_settings;
create policy "Admin users can update election settings"
on election_settings for update
to authenticated
using (is_admin())
with check (is_admin());

drop policy if exists "Admin can view own admin record" on admin_users;
create policy "Admin can view own admin record"
on admin_users for select
to authenticated
using (user_id = auth.uid());

drop policy if exists "Service role can manage admin users" on admin_users;
create policy "Service role can manage admin users"
on admin_users for all
to service_role
using (true)
with check (true);

-- =============================================
-- 4. LOGIKA BISNIS (STORED PROCEDURES / RPC)
-- =============================================

-- FUNGSI 1: IMPORT DPT (Dipakai Admin/Panitia)
-- Fungsi ini otomatis meng-hash kode akses sebelum disimpan ke DB.
create or replace function admin_add_voter(
  p_nim text,
  p_name text,
  p_access_code_plain text -- Kode asli (misal: "X7K9L")
) returns void as $$
begin
  if not is_admin() then
    raise exception 'Unauthorized';
  end if;

  insert into voters (nim, name, access_code_hash)
  values (
    p_nim, 
    p_name, 
    crypt(p_access_code_plain, gen_salt('bf')) -- Enkripsi pakai BCrypt
  );

  insert into audit_logs (action, details)
  values ('ADMIN_ACTION', jsonb_build_object('action', 'ADD_VOTER', 'nim', p_nim));
end;
$$ language plpgsql security definer set search_path = public;

-- FUNGSI 2: CORE VOTING MECHANISM (Jantung Aplikasi)
-- Fungsi ini menangani: Validasi, Cek Double Vote, dan Insert Suara dalam 1 Transaksi.
create or replace function submit_vote(
  p_nim text,
  p_access_code_plain text,
  p_candidate_id bigint,
  p_client_info jsonb -- Data IP/Browser dari frontend
) returns jsonb as $$
declare
  v_voter voters%rowtype;
  v_settings election_settings%rowtype;
  v_rate vote_rate_limits%rowtype;
  v_headers jsonb;
  v_ip text;
  v_ua text;
  v_client_key text;
  v_now timestamptz := timezone('utc'::text, now());
  v_fail_count int;
  v_window interval := interval '10 minutes';
  v_max_fail int := 25;
begin
  select * into v_settings from election_settings where id = 1;
  if not found or v_settings.is_voting_open is distinct from true then
    insert into audit_logs (action, details)
    values ('LOGIN_FAIL', p_client_info || jsonb_build_object('reason', 'Voting closed', 'nim', p_nim));
    raise exception 'Pemungutan suara sedang ditutup.';
  end if;

  v_headers := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  v_ip := nullif(v_headers->>'cf-connecting-ip', '');
  if v_ip is null then v_ip := nullif(split_part(coalesce(v_headers->>'x-forwarded-for', ''), ',', 1), ''); end if;
  if v_ip is null then v_ip := nullif(v_headers->>'x-real-ip', ''); end if;
  if v_ip is null then v_ip := nullif(p_client_info->>'ip', ''); end if;
  if v_ip is null then v_ip := 'unknown'; end if;

  v_ua := nullif(v_headers->>'user-agent', '');
  if v_ua is null then v_ua := nullif(p_client_info->>'userAgent', ''); end if;
  if v_ua is null then v_ua := 'unknown'; end if;

  v_client_key := encode(digest(v_ip || '|' || v_ua, 'sha256'), 'hex');

  select * into v_rate from vote_rate_limits where client_key = v_client_key;
  if found and v_rate.blocked_until is not null and v_rate.blocked_until > v_now then
    insert into audit_logs (action, details)
    values (
      'LOGIN_FAIL',
      p_client_info || jsonb_build_object('reason', 'Rate limited', 'nim', p_nim, 'client_key', v_client_key, 'blocked_until', v_rate.blocked_until)
    );
    raise exception 'Terlalu banyak percobaan dari jaringan Anda. Silakan tunggu beberapa menit lalu coba lagi.';
  end if;

  -- 1. Cari data voter berdasarkan NIM
  select * into v_voter from voters where nim = p_nim for update;

  -- 2. Validasi: Apakah NIM ada?
  if not found then
    if exists (select 1 from vote_rate_limits where client_key = v_client_key) then
      update vote_rate_limits
      set
        fail_count = case
          when first_fail_at is null or first_fail_at < (v_now - v_window) then 1
          else fail_count + 1
        end,
        first_fail_at = case
          when first_fail_at is null or first_fail_at < (v_now - v_window) then v_now
          else first_fail_at
        end,
        updated_at = v_now
      where client_key = v_client_key
      returning fail_count into v_fail_count;
    else
      insert into vote_rate_limits (client_key, fail_count, first_fail_at, blocked_until, updated_at)
      values (v_client_key, 1, v_now, null, v_now)
      returning fail_count into v_fail_count;
    end if;

    if coalesce(v_fail_count, 0) >= v_max_fail then
      update vote_rate_limits
      set blocked_until = v_now + v_window,
          updated_at = v_now
      where client_key = v_client_key;
    end if;

    insert into audit_logs (action, details) values ('LOGIN_FAIL', p_client_info || jsonb_build_object('reason', 'NIM not found', 'nim', p_nim));
    raise exception 'NIM tidak terdaftar dalam DPT.';
  end if;

  -- 3. Validasi: Apakah Password/Token Benar? (Cek Hash)
  if v_voter.access_code_hash != crypt(p_access_code_plain, v_voter.access_code_hash) then
    if exists (select 1 from vote_rate_limits where client_key = v_client_key) then
      update vote_rate_limits
      set
        fail_count = case
          when first_fail_at is null or first_fail_at < (v_now - v_window) then 1
          else fail_count + 1
        end,
        first_fail_at = case
          when first_fail_at is null or first_fail_at < (v_now - v_window) then v_now
          else first_fail_at
        end,
        updated_at = v_now
      where client_key = v_client_key
      returning fail_count into v_fail_count;
    else
      insert into vote_rate_limits (client_key, fail_count, first_fail_at, blocked_until, updated_at)
      values (v_client_key, 1, v_now, null, v_now)
      returning fail_count into v_fail_count;
    end if;

    if coalesce(v_fail_count, 0) >= v_max_fail then
      update vote_rate_limits
      set blocked_until = v_now + v_window,
          updated_at = v_now
      where client_key = v_client_key;

      insert into audit_logs (action, details)
      values (
        'LOGIN_FAIL',
        p_client_info || jsonb_build_object('reason', 'Rate limit triggered', 'nim', p_nim, 'fail_count', v_fail_count, 'client_key', v_client_key)
      );

      raise exception 'Terlalu banyak percobaan dari jaringan Anda. Silakan tunggu beberapa menit lalu coba lagi.';
    end if;

    insert into audit_logs (action, details) values ('LOGIN_FAIL', p_client_info || jsonb_build_object('reason', 'Wrong Token', 'nim', p_nim));
    raise exception 'Kode Akses salah. Silakan cek surat undangan.';
  end if;

  -- 4. Validasi: Apakah Sudah Memilih? (Cegah Double Voting)
  if v_voter.has_voted then
    insert into audit_logs (action, details) values ('LOGIN_FAIL', p_client_info || jsonb_build_object('reason', 'Already Voted', 'nim', p_nim));
    raise exception 'Maaf, NIM ini sudah digunakan untuk memilih.';
  end if;

  -- 5. EKSEKUSI (Jika semua lolos)
  delete from vote_rate_limits where client_key = v_client_key;

  -- Update status pemilih
  update voters set has_voted = true where nim = p_nim;
  
  -- Masukkan suara (Tanpa identitas pemilih)
  insert into votes (candidate_id) values (p_candidate_id);
  
  -- Catat Log Sukses
  insert into audit_logs (action, details) values ('VOTE_SUCCESS', jsonb_build_object('event', 'VOTE_SUCCESS'));

  return jsonb_build_object('status', 'success', 'message', 'Terima kasih, suara Anda telah direkam.');
end;
$$ language plpgsql security definer set search_path = public;

-- FUNGSI 3: DASHBOARD REKAP (Realtime Count)
-- Mengambil hasil suara tanpa perlu download ribuan baris data (Efisien)
create or replace function get_vote_recap()
returns table (candidate_name text, total_votes bigint) as $$
begin
  return query
  select 
    c.name as candidate_name,
    count(v.id) as total_votes
  from candidates c
  left join votes v on c.id = v.candidate_id
  group by c.id, c.name
  order by total_votes desc;
end;
$$ language plpgsql security definer set search_path = public;

revoke all on function admin_add_voter(text, text, text) from public;
grant execute on function admin_add_voter(text, text, text) to authenticated;

revoke all on function submit_vote(text, text, bigint, jsonb) from public;
grant execute on function submit_vote(text, text, bigint, jsonb) to anon, authenticated;

revoke all on function get_vote_recap() from public;
grant execute on function get_vote_recap() to anon, authenticated;

-- =============================================
-- 5. DATA DUMMY (Untuk Test Awal)
-- =============================================
-- Masukkan 2 Kandidat Contoh
insert into candidates (name, vision, mission, photo_url)
select v.name, v.vision, v.mission, v.photo_url
from (
  values
    ('Bapak Budi Santoso', 'Menuju Desa Makmur', '1. Membangun jalan. 2. Internet gratis.', 'https://placehold.co/400'),
    ('Ibu Siti Aminah', 'Desa Sehat & Cerdas', '1. Posyandu keliling. 2. Beasiswa anak desa.', 'https://placehold.co/400')
) as v(name, vision, mission, photo_url)
where not exists (
  select 1 from candidates c where c.name = v.name
);

-- Masukkan 1 Pemilih Contoh (NIM: 22351001, Kode: RAHASIA)
-- Kita pakai fungsi admin_add_voter biar otomatis di-hash
do $$
begin
  perform admin_add_voter('22351001', 'Mahasiswa Test', 'RAHASIA');
exception
  when others then null;
end $$;